spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.129.7.79:3306/drom?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 1280483820zz
  jackson:
    date-format: yyyy-MM-dd


server:
  port: 8888
  servlet:
    context-path: /


mybatis:
  mapper-locations: com/yanzhen/mapper/*.xml

pagehelper:
  helper-dialect: mysql


